version: '3.8'
services:
    uprun_puma:
      build:
        context: ./
        dockerfile: ./containers/puma/Dockerfile
      environment:
        RAILS_ENV: production
      volumes:
        - ./log:/app/log # persist logs
        - ./data:/app/data # persist photos
        - ./db:/app/db # persist db
        - /app/public
        - /app/tmp
      networks:
        - web_network
      env_file:
        - prod.envs
    uprun_nginx:
      build:
        context: ./
        dockerfile: ./containers/nginx/Dockerfile
      networks:
        - web_network
      volumes_from:
        - uprun_puma
      depends_on:
        - uprun_puma

networks:
  web_network:
    external: true
