development:
  download_tmp_path: '/tmp/files'
  spool_dir: '/mnt/upfgphotos2/dev/photo'
  avatar_dir: '/mnt/upfgphotos2/dev/avatar'
  thumbnail_large_dir: '/mnt/upfgphotos2/dev/thumbnail_large'
  thumbnail_small_dir: '/mnt/upfgphotos2/dev/thumbnail_small'
  page_window_size: 50

test:
  download_tmp_path: '/tmp/files'
  spool_dir: '/mnt/upfgphotos2/test/photo'
  avatar_dir: '/mnt/upfgphotos2/test/avatar'
  thumbnail_large_dir: '/mnt/upfgphotos2/test/thumbnail_large'
  thumbnail_small_dir: '/mnt/upfgphotos2/test/thumbnail_small'
  page_window_size: 50

production:
  download_tmp_path: '/tmp/files'
  spool_dir: '/mnt/upfgphotos2/production/photo'
  avatar_dir: '/mnt/upfgphotos2/production/avatar'
  thumbnail_large_dir: '/mnt/upfgphotos2/production/thumbnail_large'
  thumbnail_small_dir: '/mnt/upfgphotos2/production/thumbnail_small'
  page_window_size: 50

