development:
  download_tmp_path: '/tmp/files'
  spool_dir: '/mnt/upfgphotos/dev'
  photo_resie_rate: 0.1
  page_window_size: 100

test:
  download_tmp_path: '/tmp/files'
  spool_dir: '/mnt/upfgphotos/test'
  photo_resie_rate: 0.1
  page_window_size: 100

production:
  download_tmp_path: '/tmp/files'
  spool_dir: '/mnt/upfgphotos/prod'
  photo_resie_rate: 0.1
  page_window_size: 100

