# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'CPc5mWFIcv16cwgXKtjlhTcvs'
  twitter_api_secret: 'Ps3VeGYI5MN0V6G6loaQW9yVoalQsFbnZHzlMQbGGfjfYwYZiq'

development:
  secret_key_base: 9f52e5c1dab94ece5f2c33832127445b403838c623e30112512945b558d8987744f1a05e77db8feb499148df0a2a2515898104424db15e51043e33fed6b0077c
  <<: *default_twitter

test:
  secret_key_base: cbb33301b13f7d78759fd691f0fc5aed6d611860d01222f56abf078a7068c7afa89afc2429a1d64feea52a711de43efe83c711e971748f51795dc859b8b50647
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
